### ISSUE TITLE
[1.19] Compatibility with Better Animations Collection mod

### ISSUE THREAD

**Issue by Fuzss** [yurisuika/Dyed#1]
Hey there, nice mod.

So this mod is incompatible with my [Better Animations Collection](https://www.curseforge.com/minecraft/mc-mods/better-animations-collection) mod, as it replaces the vanilla horse armor layer which my mod is then unable to find to replace the horse model for (see https://github.com/Fuzss/betteranimationscollection/issues/10).

I could add dedicated integration for your mod on my end, but it would be much cooler if you could just simplify your code a little so that everything works without any dedicated integration.

So my suggestion is this: Since you're using Mixins anyways, why not place a mixin in `HorseArmorLayer` directly instead of replacing the layer? In the vanilla layer you can simply hook into the `HEAD` of `HorseArmorLayer::render` and run from there. 

Would be very neat if you could make that change for both mods to be compatible.

**Comment by yurisuika** [comment]
Thanks for the suggestion! I have gotten it working in 1.19 as far as I can tell, all fine on Forge 43.1.43.

I'll push the updated stuff here once I get the rest of the versions done, do let me know if all seems adequate!

**Comment by Fuzss** [comment]
Awesome, thanks!
