### ISSUE TITLE
Duplicated Horse Glitch

### ISSUE THREAD

**Issue by Fyoncle** [yurisuika/Dyed#2]
While using Fresh Animations with EMF & ETF the horse armor gets duplicated and saddle clips through it, it's because of the Dyed mod and its not because of the other mods installed.

https://github.com/yurisuika/Dyed/assets/63975256/81e331a2-5ae3-4540-bb81-c5bbc796adac

**Comment by yurisuika** [comment]
From what I can tell it looks fixed on my end, but I don't have that fancy camera, so let me know if it all looks fine to you.

https://github.com/yurisuika/Dyed/actions/runs/8994044649

**Comment by Fyoncle** [comment]
> From what I can tell it looks fixed on my end, but I don't have that fancy camera, so let me know if it all looks fine to you.
> 
> https://github.com/yurisuika/Dyed/actions/runs/8994044649

The update is already 2 months ago on modrinth, how its fixed? i tried now and its still the same.

**Comment by yurisuika** [comment]
look at the link
