### ISSUE TITLE
Game dont start even having the correct versions of Minecraft and Java

### ISSUE THREAD

**Issue by Yoni664** [yurisuika/Dyed#4]
Dyed version 1.1.3 for minecraft 1.20.X has the following problems when starting the game: 
The 'Dyed' (dyed) 1.1.3 mod requires any version after 1.20.4 of 'Minecraft' (minecraft), but you only have one wrong version: 1.20.1!
The 'Dyed' (dyed) 1.1.3 mod requires 'OpenJDK 64-Bit Server VM' (java) version 21 or later, but you only have the wrong version: 17!

My Minecraft version: 1.20.1
My Fabric version: 0.15.11
My Java Version: 22.0.1

I am using the build from the following link: 
https://github.com/yurisuika/Dyed/actions/runs/8994044649

I just was thinking that this version of the mod is made for Minecraft >= 1.20.4 and not for any version of 1.20.
If so, it would be good to specify the correct version in the Build and not leave it for any version "1.20.X"

![Captura2](https://github.com/yurisuika/Dyed/assets/143241985/3ab86fcf-4d9d-45d5-bfb3-deff08fbd5c5)
![Captura](https://github.com/yurisuika/Dyed/assets/143241985/5d27e04f-3aad-4e48-95d6-f7d36cac3cee)

**Comment by yurisuika** [comment]
The 1.20.x branch is only for 1.20.5+, if you want to use 1.20.1 you must use the "up to" 1.20.4 branch. The "x" is so the branch name does not have to change for any additional MC patch versions. This only applies to the github branch names and is not reflected anywhere in the code. This is intended.
