### ISSUE TITLE
Better Page Markdownings

### ISSUE THREAD

**Issue by Fyoncle** [yurisuika/Dyed#5]
1. I think Modrinth page missing a lot from markdown
2. Also missing a comparison with vanilla and this mod, because i first didn't even understand what that mod does at all.
3. Also this thing that you put − × − × − × − × − × − × − × − × − × − × − × − × − × − × − × − × − × − × − × − × − × − × − × − × − × − × − × −
Which is very useless because you can use a single # with leaving space up above it and below it so it will create the line for you.
4. The trailer, neither the gallery doesn't state __anything__ related to the mod so that might be why people not usually figuring it out from the page so early like i didn't mod.
5. Logo has a LOTTA empty spots
![image](https://github.com/user-attachments/assets/684bc4c3-348a-4ef6-8c28-bb06b46ace95)
6. FAQ Missing the FAQ title, and also it does not answer if i can use it in my modpack or not, neither if i can in what conditions.
7. It sounds like we require 3 loaders just to run the mod, why you writed it this way? 
![image](https://github.com/user-attachments/assets/eea96a9c-157b-43df-bbeb-234084e23b24)

**Comment by yurisuika** [comment]
lol

**Comment by Fyoncle** [comment]
> lol

...?
